umbral-pre/src/capsule.rs
umbral-pre/src/constants.rs
umbral-pre/src/hashing.rs
umbral-pre/src/hashing_ds.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/lib.rs

Fixes #28
As we have discussed, we need to keep the DSTs, but they're better off hidden in the respective functions.
What do you think, keep strings as tags, or use single bytes to make it a little more portable?

Get rid of exposed domain separation tags and use dedicated functions instead

---

umbral-pre/Cargo.toml
umbral-pre/src/capsule_frag.rs
umbral-pre/src/curve.rs
umbral-pre/src/dem.rs
umbral-pre/src/hashing.rs
umbral-pre/src/hashing_ds.rs
umbral-pre/src/params.rs

Time to stop with direct pushing to upstream and start proper procedures.
- remove the use of all extraneous hashing (fixes #2), leaving only SHA256
- in particular, halve the range of `unsafe_hash_to_point()`, since SHA256 gives us 32 bytes and we need 33 to fully define a point. 
Not implementing the standardized hash-to-point in this PR, see #35

Hash functions cleanup

---

umbral-pre-python/Cargo.toml
umbral-pre-python/docs/index.rst
umbral-pre-python/example/example.py
umbral-pre-python/src/lib.rs
umbral-pre-python/umbral_pre/__init__.py
umbral-pre-python/umbral_pre/__init__.pyi
umbral-pre-wasm/README.md
umbral-pre-wasm/example/index.js
umbral-pre-wasm/src/lib.rs
umbral-pre/Cargo.toml
umbral-pre/src/capsule.rs
umbral-pre/src/capsule_frag.rs
umbral-pre/src/curve.rs
umbral-pre/src/dem.rs
umbral-pre/src/hashing.rs
umbral-pre/src/hashing_ds.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/keys.rs
umbral-pre/src/lib.rs
umbral-pre/src/params.rs
umbral-pre/src/pre.rs

Necessary adjustments to reach binary compatibility with PyUmbral. See the related https://github.com/nucypher/pyUmbral/pull/263
- stopped bundling `Parameters` with objects and decoupled `u` from `g` (as decided in #3)
- renamed `UmbralDEM` to `DEM` (we have namespaces for that)
- replaced ChaCha with XChaCha for DEM
- used domain separation tags for all instances of hashing 
- exposed serialization via `__bytes__()` and `from_bytes()` in Python bindings (part of #11)
- added `SecretKeyFactory` for secret key derivation
- changed order of parameters in `CapsuleFrag.verify()` to match the rest of the library (and the Python version)
- various internal naming changes
Effectively fixes #27, although nothing really changed in the binary format on the Rust side (except for domain tags, …

Interfacing with Python

---

umbral-pre-python/Cargo.toml
umbral-pre-python/src/lib.rs
umbral-pre-python/umbral_pre/__init__.py
umbral-pre-wasm/Cargo.toml
umbral-pre-wasm/README.md
umbral-pre-wasm/example/index.js
umbral-pre-wasm/src/lib.rs
umbral-pre/Cargo.toml
umbral-pre/src/capsule.rs
umbral-pre/src/capsule_frag.rs
umbral-pre/src/curve.rs
umbral-pre/src/dem.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/keys.rs
umbral-pre/src/lib.rs
umbral-pre/src/pre.rs
umbral-pre/src/traits.rs

Based on top of #50
- Move `HasName` trait from Python bindings into the main library and rename it to `HasTypeName`
- Add a `Display` implementation for public types in the main library and use it in Python/WASM bindings (was formerly only implemented in Python bindings)
- Remove `GenericError` from Python bindings; in the cases where it is used it can be replaced by `ValueError`
- `from_array()` can only return a `ConstructionError` now, and not a size mismatch error (because the array size is already statically asserted by the compiler)
- Add `toBytes()/fromBytes()/toString()` methods to public objects in WASM bindings. Fixes #11 (if we decide to use some third-party serialization, like `protobuf`, it should be made a separate issue)
- Merge …

Trait implementations and error handling

---

umbral-pre-python/docs/index.rst
umbral-pre-python/example/example.py
umbral-pre-python/src/lib.rs
umbral-pre-python/umbral_pre/__init__.pyi
umbral-pre-wasm/README.md
umbral-pre-wasm/src/lib.rs
umbral-pre/src/capsule.rs
umbral-pre/src/capsule_frag.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/keys.rs
umbral-pre/src/lib.rs
umbral-pre/src/pre.rs

Paired with https://github.com/nucypher/pyUmbral/pull/271
See the rationale there. Briefly, this is a more used way, and it coincides with [RustCrypto API](https://docs.rs/elliptic-curve/0.10.1/elliptic_curve/struct.SecretKey.html#method.public_key)

Add `SecretKey::public_key()` shortcut

---

umbral-pre/Cargo.toml

The only stable features of `getrandom` are:
- `"std"`
- `"rdrand"`
- `"js"`
- `"custom"`
Setting `"wasm-bindgen"` isn't guaranteed to work going forward (and does nothing currently).
Just to note, your crate is also setting the `"js"` feature. This is basically saying, "every `wasm32-unknown-unknown` user of this crate is either on Node.js or Client-side Web, and has access to JavaScript". This is a very reasonable restriction for your use case (as this project seems to have explicit JavaScript bindings), but we always want dependent library crates to be aware of this.
Signed-off-by: Joe Richey <joerichey@google.com>

getrandom: Don't set "wasm-bindgen"

---

CHANGELOG.md
umbral-pre-python/docs/index.rst
umbral-pre-python/src/lib.rs
umbral-pre-python/umbral_pre/__init__.pyi
umbral-pre-wasm/src/lib.rs
umbral-pre/Cargo.toml
umbral-pre/src/capsule.rs
umbral-pre/src/curve.rs
umbral-pre/src/dem.rs
umbral-pre/src/hashing.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/keys.rs
umbral-pre/src/lib.rs
umbral-pre/src/pre.rs
umbral-pre/src/secret_box.rs
umbral-pre/src/traits.rs

Fixes #8 (to the extent Rust allows, at least)
The main principles of keeping secret data secret in Rust are:
- put it in a `Box` to prevent stack allocation (which may lead to unwanted copies left on stack)
- have a `Drop` implementation that zeroizes secret data
We have secret data belonging to three kinds of foreign types:
- those for which `Zeroize` is defined, but which are not zeroized on drop by default (e.g. RustCrypto `Scalar`)
- those for which `Zeroize` is not defined (e.g. `GenericArray`)
- those for which `Zeroize` is not defined, but which are zeroized on drop (e.g. RustCrypto `SecretKey`). Note that RustCrypto `SigningKey` was not zeroized until recently - it is since `ecdsa` 0.12.2
Plus, of course, our own types, but for them at least we can define traits.
Changes in the …

Make sure secret data is zeroized on drop and not copied around

---

.github/workflows/umbral-pre.yml
CHANGELOG.md
umbral-pre/Cargo.toml
umbral-pre/src/capsule.rs
umbral-pre/src/capsule_frag.rs
umbral-pre/src/curve.rs
umbral-pre/src/dem.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/keys.rs
umbral-pre/src/lib.rs
umbral-pre/src/pre.rs
umbral-pre/src/traits.rs

Fixes #13
Based on top of #53 
Changes:
- added a feature `default-rng` (enabled by default), that enables the use of the system RNG. Without it, `SecretKey::random()`, `SecretKeyFactory::random()`, `encrypt()`, `generate_kfrags()`, and `reencrypt()` are not available; one has to use the `*_with_rng()` options and provide an RNG manually. 
- enabled compilation on an ARM target (`thumbv7em-none-eabi`) in the CI
For reviewers:
- Should the default-rng versions have the "default" names, or the ones with the explicit RNG? That is, `random_with_rng()` and `random()`, or `random()` and `random_with_default_rng()` (or whatever other name; this might be too long). RustCrypto uses explicit RNG everywhere, so the latter variant would be closer to it, but the default RNG functions are the ones used …

Fix compilation on `thumbv7em-none-eabi` target

---

.github/workflows/umbral-pre.yml
CHANGELOG.md
umbral-pre/Cargo.toml
umbral-pre/bench/bench.rs
umbral-pre/src/bench.rs
umbral-pre/src/capsule.rs
umbral-pre/src/lib.rs

Fixes #9
- added benchmarks for `Capsule::from_public_key()`, `Capsule::open_original()`, and `Capsule::open_reencrypted()`
- internal benchmarks are only run with the feature `bench-internals`
- added benchmarks for `encrypt()`, `decrypt_original()`, `generate_kfrags()`, `reencrypt()`, and `open_reencrypted()` (only for 2 out of 3 scenarios)
- added benchmarking to Github actions (build only, running them is too slow)

Add benchmarks for the whole PRE scenario and some internals

---

CHANGELOG.md
umbral-pre-python/docs/index.rst
umbral-pre-python/src/lib.rs
umbral-pre-python/umbral_pre/__init__.pyi
umbral-pre-wasm/src/lib.rs
umbral-pre/src/capsule_frag.rs

Fixes #58
`VerifiedCapsuleFrag::from_verified_bytes()` was added to support caching of capsule frags on the receiver's side (by analogy with the existing `VerifiedKeyFrag::from_verified_bytes()`), when there is no need to re-verify on deserialization.

Add `VerifiedCapsuleFrag::from_verified_bytes()`

---

CHANGELOG.md
umbral-pre-python/docs/index.rst
umbral-pre-python/src/lib.rs
umbral-pre-python/umbral_pre/__init__.pyi
umbral-pre-wasm/src/lib.rs
umbral-pre/src/keys.rs

- Added `SecretKeyFactory::secret_key_factory_by_label()` (fixes #59)
- Added `SecretKeyFactory::from_secure_randomness()` and `seed_size()` (fixes #57)
- Reduced the key material size in `SecretKeyFactory` from 64 to 32 bytes (as discussed with @cygnusv). 
Note that the derived key size is still 64 bytes in `secret_key_by_label()` to reduce aliasing when converting the derived bytes into a scalar (with modulo reduction). Since they pass through a hash function, I'm not sure if that's important.
Also, in Discord @cygnusv suggested using `Scalar::from_bytes_reduced()` instead of `from_digest()` to avoid the hashing step in `secret_key_by_label()`. I have the following concerns about it:
- it takes a `FieldBytes` argument, which indicates that it's a semi-internal function - there is no …

Additional `SecretKeyFactory` constructors

---

umbral-pre/src/capsule.rs
umbral-pre/src/capsule_frag.rs
umbral-pre/src/curve.rs
umbral-pre/src/dem.rs
umbral-pre/src/hashing.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/keys.rs

A new lint in `clippy` provides warnings about needless borrows.

Fix needless borrows

---

CHANGELOG.md
Cargo.toml
umbral-pre/Cargo.toml
umbral-pre/src/capsule.rs
umbral-pre/src/capsule_frag.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/keys.rs
umbral-pre/src/lib.rs
umbral-pre/src/serde.rs

- adds `Serialize`/`Deserialize` implementations for `PublicKey`, `Signature`, `Capsule`, `KeyFrag`, `CapsuleFrag`
- for human-readable formats, `PublicKey` is serialized as hex, and the rest in base64-encoded form
Note: all the serializations simply use the bytestring produced by `to_array()` for binary formats, and the b64 encoding of it for human-readable formats; this helps preserve compatibility with `pyumbral` (as opposed to implementing `Serialize` for `CurveScalar` and `CurvePoint`, and deriving the rest).
For now, not including any `serde` support for `Verified*` objects - they won't be used as nested fields in any protocol objects, so the existing serialization support is enough. Same for the secret objects (`SecretKey`, `SecretKeyFactory`).
For future: we could expose the …

`serde` support

---

CHANGELOG.md
umbral-pre-python/docs/index.rst
umbral-pre-python/src/lib.rs
umbral-pre-python/umbral_pre/__init__.pyi
umbral-pre-wasm/src/lib.rs
umbral-pre/src/pre.rs

Following the standard terminology in `nucypher`

Rename "num_kfrags" to "shares"

---

CHANGELOG.md
umbral-pre-python/docs/index.rst
umbral-pre-python/example/example.py
umbral-pre-python/src/lib.rs
umbral-pre-python/umbral_pre/__init__.pyi
umbral-pre-wasm/README.md
umbral-pre-wasm/examples/bundler/index.js
umbral-pre-wasm/examples/node/index.js
umbral-pre-wasm/examples/react/src/App.js
umbral-pre-wasm/examples/webpack-5-experiments/index.js
umbral-pre-wasm/src/lib.rs
umbral-pre/src/keys.rs
umbral-pre/src/lib.rs

Fixes #33 
- renames `SecretKeyFactory::secret_key_by_label()`/`secret_factory_by_label()` -> `make_key()`/`make_factory()`. The former names were way too wordy.
- replaces remaining (from #69) instances of `m`/`n` with `threshold`/`shares`.
- replaces `verifying_key` parameter in `Signature::verify()` with `verifying_pk` - it is called like that everywhere else.

Naming fixes

---

.github/workflows/umbral-pre.yml
CHANGELOG.md
umbral-pre/Cargo.toml
umbral-pre/src/capsule.rs
umbral-pre/src/capsule_frag.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/keys.rs
umbral-pre/src/lib.rs
umbral-pre/src/pre.rs

`serde` is a pretty fat crate and is not needed for JS/Python bindings (and possibly not needed by many users of the main crate either). So this PR hides it under an optional feature.
Also it adds a list of available feature to the docs and marks gated methods with a `doc` attribute.

Gate `serde` support under a feature

---

CHANGELOG.md
umbral-pre-python/docs/index.rst
umbral-pre-python/src/lib.rs
umbral-pre-python/umbral_pre/__init__.pyi
umbral-pre-wasm/src/lib.rs
umbral-pre/bench/bench.rs
umbral-pre/src/bench.rs
umbral-pre/src/capsule.rs
umbral-pre/src/capsule_frag.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/pre.rs

Fixes #73
- adds `KeyFrag::skip_verification()`
- adds `VerifiedKeyFrag::to_unverified()`
- adds `CapsuleFrag::skip_verification()`
- adds `VerifiedCapsuleFrag::to_unverified()`
- adds corresponding methods to Python and WASM bindings

Add skip_verification() and to_unverified() to kfrags/cfrags

---

.github/workflows/wheels.yml
CHANGELOG.md
umbral-pre-python/MANIFEST.in
umbral-pre-python/replace_version.py

- add docs and examples in the manifest
- fix the path to `umbral-pre` at `sdist` CI step (fixes #80)

Fix python sdist

---

.github/workflows/umbral-pre.yml
.github/workflows/workspace.yml
CHANGELOG.md
Cargo.toml
umbral-pre-python/Cargo.toml
umbral-pre-wasm/Cargo.toml
umbral-pre-wasm/src/lib.rs
umbral-pre/Cargo.toml
umbral-pre/src/bindings_python.rs
umbral-pre/src/capsule.rs
umbral-pre/src/capsule_frag.rs
umbral-pre/src/curve.rs
umbral-pre/src/hashing.rs
umbral-pre/src/hashing_ds.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/keys.rs
umbral-pre/src/lib.rs

- bumps `k256` dependency to 0.10.1 (.1 supports `ReduceNonZero<U256>` that we need), and the sub-dependencies accordingly. 
- bumps MSRV to 1.56 and rust edition to 2021 (`k256` 0.10 requirement)
- uses the new non-zero scalar functionality (reduction to a non-zero scalar and random non-zero scalars). Everywhere where non-zero scalars are used in the code they now have their own `NonZeroCurveScalar` type (a wrapper for the backend type). Fixes #39. 
- as a consequence of the previous item, `ZeroHash` errors were removed
- the methods that could previously fail because if hash-to-scalar returned 0 are now infallible.
- adds arithmetic impls for operations on `NonZeroCurveScalar` so that it could be used transparently in the code. If https://github.com/RustCrypto/traits/pull/857 is merged, …

Bump k256 version and use the new functionality

---

CHANGELOG.md
umbral-pre-python/docs/index.rst
umbral-pre-python/umbral_pre/__init__.pyi
umbral-pre-wasm/src/lib.rs
umbral-pre/bench/bench.rs
umbral-pre/src/bindings_python.rs
umbral-pre/src/capsule.rs
umbral-pre/src/capsule_frag.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/keys.rs
umbral-pre/src/lib.rs
umbral-pre/src/pre.rs

Fixes #88
The following API changes were made:
- `Signer::new()` consumes the given `SecretKey` (fixes #61).
- `KeyFrag::verify()` and `CapsuleFrag::verify()` consume the given kfrag/cfrag.
- As a consequence, `KeyFrag::verify()` and `CapsuleFrag::verify()` return the original frag on error (as a tuple with the error itself), for logging purposes (since the original object is not available anymore).
- `reencrypt()` consumes the cfrag (but not the capsule, since it wasn't being cloned inside).
- `VerifiedKeyFrag::to_unverified()` and `VerifiedCapsuleFrag::to_unverified()` were renamed to `unverify()` and consume the corresponding frag.

Remove `clone()` calls from library internals

---

CHANGELOG.md
umbral-pre-wasm/src/lib.rs
umbral-pre/Cargo.toml
umbral-pre/bench/bench.rs
umbral-pre/src/bench.rs
umbral-pre/src/curve.rs
umbral-pre/src/hashing.rs
umbral-pre/src/params.rs

Uses the upcoming functionality based on the [IETF standard](https://datatracker.ietf.org/doc/draft-irtf-cfrg-hash-to-curve/) instead of our homegrown implementation.  Fixes #35

Use the standard hash2curve implementation instead of `unsafe_hash_to_point()`

---

.github/workflows/umbral-pre.yml
.github/workflows/workspace.yml
CHANGELOG.md
umbral-pre-python/Cargo.toml
umbral-pre/Cargo.toml
umbral-pre/src/bindings_python.rs
umbral-pre/src/capsule.rs
umbral-pre/src/curve.rs
umbral-pre/src/dem.rs
umbral-pre/src/hashing.rs
umbral-pre/src/keys.rs
umbral-pre/src/lib.rs
umbral-pre/src/pre.rs
umbral-pre/src/secret_box.rs

- Bumped `k256` to 0.11, `sha2` to 0.10, `hkdf` to 0.12, `chacha20poly1305` to 0.10, and `zeroize` to 1.5 (and MSRV to 1.57), so that we could use the new `ZeroizeOnDrop` functionality. In particular, `SecretBox` and `SecretKey` now implement `ZeroizeOnDrop`. Fixes #89 
- Removed `CanBeZeroizedOnDrop`; `GenericArray` supports `Zeroize` since `generic-array` 0.14.6
- Bumped `pyo3` to 0.16
Note that it is not clear from the documentation, but `#[derive(ZeroizeOnDrop)]` works as follows: if a field is `ZeroizeOnDrop`, it is skipped, if it's `Zeroize`, it's zeroized, if it's neither, an error is raised. So e.g. in the case when it's derived for `SecretKey` there won't be double zeroization (because the `k256::SecretKey` implements `ZeroizeOnDrop` itself), but rather a compile-time check that …

Bump crate versions

---

CHANGELOG.md
umbral-pre-python/umbral_pre/__init__.pyi

- Add missing `self` parameters to instance methods
- Add explicit `__bytes__()` methods

Fix some typos and add missing methods to Python typing stubs

---

.github/workflows/workspace.yml
CHANGELOG.md
umbral-pre/src/bindings_python.rs
umbral-pre/src/capsule.rs
umbral-pre/src/capsule_frag.rs
umbral-pre/src/dem.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/keys.rs
umbral-pre/src/pre.rs
umbral-pre/src/traits.rs

- Fix `clippy` warnings about missing `Eq`
- Disable `borrow_deref_ref` warning temporarily, since it is triggered for all PyO3 macro-generated methods
- Run `clippy` on stable instead of MSRV in the CI

Fix some clippy warnings

---

umbral-pre-wasm/Cargo.toml
umbral-pre-wasm/src/lib.rs

- `wee_alloc` has not been updated in a few years, and Dependabot shows a warning about it being unmaintained. Removing it does not even change the wasm size too much - 263kb to 269kb.
- Also removed an old exception for `clippy`; `wasm-bindgen` seems to have fixed the problem

Remove `wee_alloc`

---

CHANGELOG.md
umbral-pre-python/umbral_pre/__init__.pyi
umbral-pre/src/bindings_python.rs
umbral-pre/src/bindings_wasm.rs
umbral-pre/src/keys.rs

Returns `SecretKey` serialization functions removed in #110, because they do help in some scenarios. Exported as `to_be_bytes()`/`try_from_be_bytes()`
Also fixes a bug in the Python bindings for `SecretKeyFactory::make_secret()` introduced in #110.

SecretKey serialization

---

.github/workflows/umbral-pre.yml
CHANGELOG.md
umbral-pre-python/Cargo.toml
umbral-pre/Cargo.toml
umbral-pre/src/curve.rs
umbral-pre/src/dem.rs
umbral-pre/src/hashing.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/keys.rs
umbral-pre/src/serde_bytes.rs

- Bump `rmp-serde` to 1, `base64` to 0.21, and `pyo3` to 0.17.
- Remove second-level dependencies where applicable (e.g. use `generic_array::typenum` instead of `typenum`)
- Don't use `getrandom/js` unless building WASM bindings

Bump and group dependencies

---

CHANGELOG.md
umbral-pre-python/umbral_pre/__init__.pyi
umbral-pre/src/bindings_python.rs
umbral-pre/src/bindings_wasm.rs
umbral-pre/src/capsule.rs
umbral-pre/src/capsule_frag.rs
umbral-pre/src/keys.rs
umbral-pre/src/lib.rs
umbral-pre/src/pre.rs

- Added `Signature::to_be_bytes()`, `Capsule::to_bytes_simple()`, and `CapsuleFrag::to_bytes_simple()` to use in Ethereum contracts.
Also:
- Added the missing `VerifiedCapsuleFrag::unverify()` method in WASM bindings.
- Added the missing `Signature::to_der_bytes()` and `from_der_bytes()` that were missing in the Rust library but present in the bindings.

Serialization methods for Eth contracts

---

.github/workflows/umbral-pre.yml

`llvm-cov` can be run on Mac too, which simplifies development. Also seems to be less buggy.

Use llvm-cov instead of tarpaulin

---

CHANGELOG.md
umbral-pre/Cargo.toml
umbral-pre/src/capsule.rs
umbral-pre/src/capsule_frag.rs
umbral-pre/src/curve.rs
umbral-pre/src/evidence.rs
umbral-pre/src/key_frag.rs
umbral-pre/src/keys.rs
umbral-pre/src/lib.rs
umbral-pre/src/params.rs
umbral-pre/src/pre.rs

It is conventional in the Rust ecosystem to have features that enable one dependency have the name of that dependency.

Rename `serde-support` feature to `serde`

---

CHANGELOG.md
umbral-pre/src/keys.rs

This matches the default serialization for `RecoverableSignature` (and for that one it is non-trivial to implement DER serialization, since we have to do it manually). So let's just use the fixed-size representation everywhere.

Use fixed-size serde serialization for signatures

---

.github/workflows/umbral-pre.yml
umbral-pre-wasm/Cargo.toml
umbral-pre/Cargo.toml

- Fixes issue with `wasm-bindgen-derive` in `nucypher-core` and `ferveo` integration: https://github.com/nucypher/nucypher-core/pull/53#issuecomment-1561189441
- Tested locally

Bump `wasm-bindgen` and `wasm-bindgen-derive` versions

---

CHANGELOG.md
umbral-pre/src/bindings_wasm.rs

**Type of PR:**
- Feature
**Required reviews:** 
- 1
**Why it's needed:**
- Related to: https://github.com/nucypher/nucypher-core/issues/56
- Downstream changes in `nucypher-core` handles transparently by a version bump

Expose `SecretKey::equals` in WASM bindings

---

.github/workflows/umbral-pre.yml
.github/workflows/wheels.yml
.github/workflows/workspace.yml
umbral-pre/src/bindings_python.rs

**Type of PR:**
- Other
**Required reviews:** 
- 1
**What this does:**
- See this issue for details: https://github.com/nucypher/ferveo/issues/153
- Related: https://github.com/nucypher/nucypher-core/pull/90

Replace deprecated `actions-rs/*` GH Actions
